### ISSUE TITLE
the Git repository for manifold_python cannot be recognized

### ISSUE THREAD

**Issue by mingmo1** [robot-learning-freiburg/CenterGrasp#4]
Hello, in the latest README file you released, regarding the download method for CenterGrasp, the Git repository for manifold_python cannot be recognized. Is it a private repository or is there an error?

**Comment by chisarie** [comment]
It is a public repository, you can see it here: https://github.com/PRBonn/manifold_python
The clone command in the readme should work, maybe you need to setup your ssh keys? Otherwise you can use https

**Comment by mingmo1** [comment]
Thanks for your reply，i don't know why i can't  find this. I searched on GitHub, but didn't get any results.
